# Generated by Django 4.1.5 on 2023-01-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Не более 150 символов, только буквы, цифры и @/./+/-/_ @/./+/-/_.', max_length=254, unique=True, verbose_name='Логин.')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=255, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакты.',
                'verbose_name_plural': 'Контакты.',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.contact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('created', models.DateTimeField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт.',
                'verbose_name_plural': 'Продукты.',
            },
        ),
        migrations.CreateModel(
            name='Retail_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.contact', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.products', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Private_trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.contact', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.products', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.retail_network', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.products', verbose_name='Продукт'),
        ),
    ]
